### ISSUE TITLE
opam install nightmare.dev fails with "Error: Library "alcotest" not found."

### ISSUE THREAD

**Issue by pewulfman** [funkywork/nightmare#22]
Step to reproduce :
- Create new folder
- opam switch create . ocaml-base-compiler.5.0.0 --deps-only -y
- opam pin add nightmare https://github.com/funkywork/nightmare.git

**Comment by gr-im** [comment]
cc @xvw @mspwn 

My suggestion is to move `nightmare.test` into a dedicated library  `nightmare_test` (with `alcotest` as a real deps and not a `{with-test}` one).

**Comment by gr-im** [comment]
I guess it is fixed. Can you try again on a empty switch @pewulfman?
